Public Class step3
    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click, Button2.Click
        Try
            step4.WebBrowser1.Document.GetElementById("registerName").SetAttribute("value", TextBox1.Text) '
            step4.WebBrowser1.Document.GetElementById("registerSchool").SetAttribute("value", TextBox2.Text) '
            step4.WebBrowser1.Document.GetElementById("registerClass").SetAttribute("value", TextBox3.Text) '
            step4.WebBrowser1.Document.GetElementById("registerSitNo").SetAttribute("value", TextBox4.Text) '
            step4.WebBrowser1.Document.GetElementById("registerAddress").SetAttribute("value", TextBox5.Text) '
            step4.WebBrowser1.Document.GetElementById("registerTEL").SetAttribute("value", TextBox6.Text) '
            step4.WebBrowser1.Document.GetElementById("emergencyName").SetAttribute("value", TextBox7.Text) '
            step4.WebBrowser1.Document.GetElementById("emergencyRelation").SetAttribute("value", TextBox8.Text) '
            step4.WebBrowser1.Document.GetElementById("emergencyAddress").SetAttribute("value", TextBox9.Text) '
            step4.WebBrowser1.Document.GetElementById("emergencyTEL").SetAttribute("value", TextBox10.Text) '
            step4.WebBrowser1.Document.GetElementById("emergencyMobile").SetAttribute("value", TextBox11.Text)
            step4.WebBrowser1.Document.GetElementById("emergencyMobile").SetAttribute("value", TextBox11.Text) '
            '-----------------------------------------------------------
            For Each a1 As HtmlElement In step4.WebBrowser1.Document.GetElementsByTagName("SELECT")
                '性別
                If a1.GetAttribute("name") = "registerSEX" Then
                    a1.SetAttribute("value", Mid(ComboBox1.Text, 1, 1))  'MID是函數第一個1表從第幾位開始算,第二個1表向右算幾格
                End If
                '年
                If a1.GetAttribute("name") = "registerBirthYear" Then
                    a1.SetAttribute("value", ComboBox2.Text)
                    a1.RaiseEvent("onchange")
                End If
                '月
                If a1.GetAttribute("name") = "registerBirthMonth" Then
                    a1.SetAttribute("value", ComboBox3.Text)
                    a1.RaiseEvent("onchange")
                End If
                '日
                If a1.GetAttribute("name") = "registerBirthDay" Then
                    a1.SetAttribute("value", ComboBox4.Text)
                    a1.RaiseEvent("onchange")
                End If
                If a1.GetAttribute("name") = "registerCounty" Then
                    a1.SetAttribute("value", Mid(ComboBox5.Text, 5, 2))
                    a1.RaiseEvent("onchange")
                End If
                If a1.GetAttribute("name") = "emergencyCounty" Then
                    a1.SetAttribute("value", Mid(ComboBox7.Text, 5, 2))
                    a1.RaiseEvent("onchange")
                End If

                If a1.GetAttribute("name") = "registerCountyZone" Then
                    a1.SetAttribute("value", Mid(ComboBox6.Text, 5, 3))
                    a1.RaiseEvent("onchange")
                End If
                If a1.GetAttribute("name") = "emergencyCountyZone" Then
                    a1.SetAttribute("value", Mid(ComboBox8.Text, 5, 3))
                    a1.RaiseEvent("onchange")
                End If
            Next
        Catch
            MsgBox("發生錯誤! 請檢查是否完填寫完整。", 0 + 48, "提示")
        End Try
        '------------------------------------------------------------
    End Sub
    '61
    '495
    Private Sub ComboBox5_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ComboBox5.SelectedIndexChanged, ComboBox13.SelectedIndexChanged
        If ComboBox5.Text = "新北市(01)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("金山區(208)")
            ComboBox6.Items.Add("汐止區(221)")
            ComboBox6.Items.Add("石碇區(223)")
            ComboBox6.Items.Add("平溪區(226)")
            ComboBox6.Items.Add("貢寮區(228)")
            ComboBox6.Items.Add("坪林區(232)")
            ComboBox6.Items.Add("永和區(234)")
            ComboBox6.Items.Add("土城區(236)")
            ComboBox6.Items.Add("樹林區(238)")
            ComboBox6.Items.Add("三重區(241)")
            ComboBox6.Items.Add("泰山區(243)")
            ComboBox6.Items.Add("蘆洲區(247)")
            ComboBox6.Items.Add("八里區(249)")
            ComboBox6.Items.Add("三芝區(252)")
            ComboBox6.Items.Add("板橋區(220)")
            ComboBox6.Items.Add("深坑區(222)")
            ComboBox6.Items.Add("瑞芳區(224)")
            ComboBox6.Items.Add("雙溪區(227)")
            ComboBox6.Items.Add("新店區(231)")
            ComboBox6.Items.Add("烏來區(233)")
            ComboBox6.Items.Add("中和區(235)")
            ComboBox6.Items.Add("三峽區(237)")
            ComboBox6.Items.Add("鶯歌區(239)")
            ComboBox6.Items.Add("新莊區(242)")
            ComboBox6.Items.Add("林口區(244)")
            ComboBox6.Items.Add("五股區(248)")
            ComboBox6.Items.Add("淡水區(251)")
            ComboBox6.Items.Add("石門區(253)")
            ComboBox6.Items.Add("萬里區(207)")
        End If
        If ComboBox5.Text = "宜蘭縣(02)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("宜蘭市(260)")
            ComboBox6.Items.Add("頭城鎮(261)")
            ComboBox6.Items.Add("壯圍鄉(263)")
            ComboBox6.Items.Add("羅東鎮(265)")
            ComboBox6.Items.Add("大同鄉(267)")
            ComboBox6.Items.Add("冬山鄉(269)")
            ComboBox6.Items.Add("南澳鄉(272)")
            ComboBox6.Items.Add("礁溪鄉(262)")
            ComboBox6.Items.Add("員山鄉(264)")
            ComboBox6.Items.Add("三星鄉(266)")
            ComboBox6.Items.Add("五結鄉(268)")
            ComboBox6.Items.Add("蘇澳鎮(270)")
        End If
        If ComboBox5.Text = "桃園市(03)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("中壢市(320)")
            ComboBox6.Items.Add("平鎮市(324)")
            ComboBox6.Items.Add("楊梅鎮(326)")
            ComboBox6.Items.Add("觀音鄉(328)")
            ComboBox6.Items.Add("龜山鄉(333)")
            ComboBox6.Items.Add("大溪鎮(335)")
            ComboBox6.Items.Add("大園鄉(337)")
            ComboBox6.Items.Add("龍潭鄉(325)")
            ComboBox6.Items.Add("新屋鄉(327)")
            ComboBox6.Items.Add("桃園市(330)")
            ComboBox6.Items.Add("八德市(334)")
            ComboBox6.Items.Add("復興鄉(336)")
            ComboBox6.Items.Add("蘆竹鄉(338)")
        End If
        If ComboBox5.Text = "新竹縣(04)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("竹北市(302)")
            ComboBox6.Items.Add("湖口鄉(303)")
            ComboBox6.Items.Add("新埔鎮(305)")
            ComboBox6.Items.Add("芎林鄉(307)")
            ComboBox6.Items.Add("竹東鎮(310)")
            ComboBox6.Items.Add("橫山鄉(312)")
            ComboBox6.Items.Add("北埔鄉(314)")
            ComboBox6.Items.Add("新豐鄉(304)")
            ComboBox6.Items.Add("關西鎮(306)")
            ComboBox6.Items.Add("寶山鄉(308)")
            ComboBox6.Items.Add("五峰鄉(311)")
            ComboBox6.Items.Add("尖石鄉(313)")
            ComboBox6.Items.Add("峨眉鄉(315)")
        End If
        If ComboBox5.Text = "苗栗縣(05)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("竹南鎮(350)")
            ComboBox6.Items.Add("頭份鎮(351)")
            ComboBox6.Items.Add("南庄鄉(353)")
            ComboBox6.Items.Add("後龍鎮(356)")
            ComboBox6.Items.Add("苑裡鎮(358)")
            ComboBox6.Items.Add("造橋鄉(361)")
            ComboBox6.Items.Add("公館鄉(363)")
            ComboBox6.Items.Add("泰安鄉(365)")
            ComboBox6.Items.Add("三義鄉(367)")
            ComboBox6.Items.Add("卓蘭鎮(369)")
            ComboBox6.Items.Add("三灣鄉(352)")
            ComboBox6.Items.Add("獅潭鄉(354)")
            ComboBox6.Items.Add("通霄鎮(357)")
            ComboBox6.Items.Add("苗栗市(360)")
            ComboBox6.Items.Add("頭屋鄉(362)")
            ComboBox6.Items.Add("大湖鄉(364)")
            ComboBox6.Items.Add("銅鑼鄉(366)")
            ComboBox6.Items.Add("西湖鄉(368)")
        End If
        If ComboBox5.Text = "彰化縣(07)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("彰化市(500)")
            ComboBox6.Items.Add("芬園鄉(502)")
            ComboBox6.Items.Add("秀水鄉(504)")
            ComboBox6.Items.Add("福興鄉(506)")
            ComboBox6.Items.Add("和美鎮(508)")
            ComboBox6.Items.Add("員林鎮(510)")
            ComboBox6.Items.Add("永靖鄉(512)")
            ComboBox6.Items.Add("溪湖鎮(514)")
            ComboBox6.Items.Add("埔鹽鄉(516)")
            ComboBox6.Items.Add("北斗鎮(521)")
            ComboBox6.Items.Add("埤頭鄉(523)")
            ComboBox6.Items.Add("竹塘鄉(525)")
            ComboBox6.Items.Add("大城鄉(527)")
            ComboBox6.Items.Add("二水鄉(530)")
            ComboBox6.Items.Add("花壇鄉(503)")
            ComboBox6.Items.Add("鹿港鎮(505)")
            ComboBox6.Items.Add("線西鄉(507)")
            ComboBox6.Items.Add("伸港鄉(509)")
            ComboBox6.Items.Add("社頭鄉(511)")
            ComboBox6.Items.Add("埔心鄉(513)")
            ComboBox6.Items.Add("大村鄉(515)")
            ComboBox6.Items.Add("田中鎮(520)")
            ComboBox6.Items.Add("田尾鄉(522)")
            ComboBox6.Items.Add("溪州鄉(524)")
            ComboBox6.Items.Add("二林鎮(526)")
            ComboBox6.Items.Add("芳苑鄉(528)")
        End If
        If ComboBox5.Text = "南投縣(08)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("南投市(540)")
            ComboBox6.Items.Add("中寮鄉(541)")
            ComboBox6.Items.Add("國姓鄉(544)")
            ComboBox6.Items.Add("仁愛鄉(546)")
            ComboBox6.Items.Add("集集鎮(552)")
            ComboBox6.Items.Add("魚池鄉(555)")
            ComboBox6.Items.Add("竹山鎮(557)")
            ComboBox6.Items.Add("草屯鎮(542)")
            ComboBox6.Items.Add("埔里鎮(545)")
            ComboBox6.Items.Add("名間鄉(551)")
            ComboBox6.Items.Add("水里鄉(553)")
            ComboBox6.Items.Add("信義鄉(556)")
            ComboBox6.Items.Add("鹿谷鄉(558)")
        End If
        If ComboBox5.Text = "雲林縣(09)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("斗南鎮(630)")
            ComboBox6.Items.Add("大埤鄉(631)")
            ComboBox6.Items.Add("土庫鎮(633)")
            ComboBox6.Items.Add("東勢鄉(635)")
            ComboBox6.Items.Add("崙背鄉(637)")
            ComboBox6.Items.Add("斗六市(640)")
            ComboBox6.Items.Add("古坑鄉(646)")
            ComboBox6.Items.Add("西螺鎮(648)")
            ComboBox6.Items.Add("北港鎮(651)")
            ComboBox6.Items.Add("口湖鄉(653)")
            ComboBox6.Items.Add("元長鄉(655)")
            ComboBox6.Items.Add("虎尾鎮(632)")
            ComboBox6.Items.Add("褒忠鄉(634)")
            ComboBox6.Items.Add("台西鄉(636)")
            ComboBox6.Items.Add("麥寮鄉(638)")
            ComboBox6.Items.Add("林內鄉(643)")
            ComboBox6.Items.Add("莿桐鄉(647)")
            ComboBox6.Items.Add("二崙鄉(649)")
            ComboBox6.Items.Add("水林鄉(652)")
            ComboBox6.Items.Add("四湖鄉(654)")
        End If
        If ComboBox5.Text = "嘉義縣(10)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("番路鄉(602)")
            ComboBox6.Items.Add("梅山鄉(603)")
            ComboBox6.Items.Add("阿里山(605)")
            ComboBox6.Items.Add("大埔鄉(607)")
            ComboBox6.Items.Add("鹿草鄉(611)")
            ComboBox6.Items.Add("朴子市(613)")
            ComboBox6.Items.Add("六腳鄉(615)")
            ComboBox6.Items.Add("民雄鄉(621)")
            ComboBox6.Items.Add("溪口鄉(623)")
            ComboBox6.Items.Add("布袋鎮(625)")
            ComboBox6.Items.Add("竹崎鄉(604)")
            ComboBox6.Items.Add("中埔鄉(606)")
            ComboBox6.Items.Add("水上鄉(608)")
            ComboBox6.Items.Add("太保市(612)")
            ComboBox6.Items.Add("東石鄉(614)")
            ComboBox6.Items.Add("新港鄉(616)")
            ComboBox6.Items.Add("大林鎮(622)")
            ComboBox6.Items.Add("義竹鄉(624)")
        End If
        If ComboBox5.Text = "屏東縣(13)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("屏東市(900)")
            ComboBox6.Items.Add("三地門(901)")
            ComboBox6.Items.Add("瑪家鄉(903)")
            ComboBox6.Items.Add("里港鄉(905)")
            ComboBox6.Items.Add("鹽埔鄉(907)")
            ComboBox6.Items.Add("麟洛鄉(909)")
            ComboBox6.Items.Add("內埔鄉(912)")
            ComboBox6.Items.Add("潮州鎮(920)")
            ComboBox6.Items.Add("來義鄉(922)")
            ComboBox6.Items.Add("崁頂鄉(924)")
            ComboBox6.Items.Add("南州鄉(926)")
            ComboBox6.Items.Add("東港鎮(928)")
            ComboBox6.Items.Add("佳冬鄉(931)")
            ComboBox6.Items.Add("枋寮鄉(940)")
            ComboBox6.Items.Add("春日鄉(942)")
            ComboBox6.Items.Add("車城鄉(944)")
            ComboBox6.Items.Add("恆春鎮(946)")
            ComboBox6.Items.Add("霧台鄉(902)")
            ComboBox6.Items.Add("九如鄉(904)")
            ComboBox6.Items.Add("高樹鄉(906)")
            ComboBox6.Items.Add("長治鄉(908)")
            ComboBox6.Items.Add("竹田鄉(911)")
            ComboBox6.Items.Add("萬丹鄉(913)")
            ComboBox6.Items.Add("泰武鄉(921)")
            ComboBox6.Items.Add("萬巒鄉(923)")
            ComboBox6.Items.Add("新埤鄉(925)")
            ComboBox6.Items.Add("林邊鄉(927)")
            ComboBox6.Items.Add("琉球鄉(929)")
            ComboBox6.Items.Add("新園鄉(932)")
            ComboBox6.Items.Add("枋山鄉(941)")
            ComboBox6.Items.Add("獅子鄉(943)")
            ComboBox6.Items.Add("牡丹鄉(945)")
            ComboBox6.Items.Add("滿洲鄉(947)")
        End If
        If ComboBox5.Text = "台東縣(14)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("台東市(950)")
            ComboBox6.Items.Add("綠島鄉(951)")
            ComboBox6.Items.Add("延平鄉(953)")
            ComboBox6.Items.Add("鹿野鄉(955)")
            ComboBox6.Items.Add("海端鄉(957)")
            ComboBox6.Items.Add("東河鄉(959)")
            ComboBox6.Items.Add("長濱鄉(962)")
            ComboBox6.Items.Add("金峰鄉(964)")
            ComboBox6.Items.Add("達仁鄉(966)")
            ComboBox6.Items.Add("蘭嶼鄉(952)")
            ComboBox6.Items.Add("卑南鄉(954)")
            ComboBox6.Items.Add("關山鎮(956)")
            ComboBox6.Items.Add("池上鄉(958)")
            ComboBox6.Items.Add("成功鎮(961)")
            ComboBox6.Items.Add("太麻里(963)")
            ComboBox6.Items.Add("大武鄉(965)")
        End If
        If ComboBox5.Text = "花蓮縣(15)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("花蓮市(970)")
            ComboBox6.Items.Add("新城鄉(971)")
            ComboBox6.Items.Add("吉安鄉(973)")
            ComboBox6.Items.Add("鳳林鎮(975)")
            ComboBox6.Items.Add("豐濱鄉(977)")
            ComboBox6.Items.Add("萬榮鄉(979)")
            ComboBox6.Items.Add("卓溪鄉(982)")
            ComboBox6.Items.Add("秀林鄉(972)")
            ComboBox6.Items.Add("壽豐鄉(974)")
            ComboBox6.Items.Add("光復鄉(976)")
            ComboBox6.Items.Add("瑞穗鄉(978)")
            ComboBox6.Items.Add("玉里鎮(981)")
            ComboBox6.Items.Add("富里鄉(983)")
        End If
        If ComboBox5.Text = "澎湖縣(16)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("馬公市(880)")
            ComboBox6.Items.Add("西嶼鄉(881)")
            ComboBox6.Items.Add("七美鄉(883)")
            ComboBox6.Items.Add("湖西鄉(885)")
            ComboBox6.Items.Add("望安鄉(882)")
            ComboBox6.Items.Add("白沙鄉(884)")
        End If
        If ComboBox5.Text = "基隆市(17)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("仁愛區(200)")
            ComboBox6.Items.Add("信義區(201)")
            ComboBox6.Items.Add("中山區(203)")
            ComboBox6.Items.Add("暖暖區(205)")
            ComboBox6.Items.Add("中正區(202)")
            ComboBox6.Items.Add("安樂區(204)")
            ComboBox6.Items.Add("七堵區(206)")
        End If
        If ComboBox5.Text = "新竹市(18)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("所有區(300)")
        End If
        If ComboBox5.Text = "嘉義市(20)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("嘉義市(600)")
        End If
        If ComboBox5.Text = "臺北市(30)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("中正區(100)")
            ComboBox6.Items.Add("大同區(103)")
            ComboBox6.Items.Add("松山區(105)")
            ComboBox6.Items.Add("萬華區(108)")
            ComboBox6.Items.Add("士林區(111)")
            ComboBox6.Items.Add("內湖區(114)")
            ComboBox6.Items.Add("文山區(116)")
            ComboBox6.Items.Add("中山區(104)")
            ComboBox6.Items.Add("大安區(106)")
            ComboBox6.Items.Add("信義區(110)")
            ComboBox6.Items.Add("北投區(112)")
            ComboBox6.Items.Add("南港區(115)")
        End If
        If ComboBox5.Text = "高雄市(64)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("新興區(800)")
            ComboBox6.Items.Add("前金區(801)")
            ComboBox6.Items.Add("鹽埕區(803)")
            ComboBox6.Items.Add("旗津區(805)")
            ComboBox6.Items.Add("三民區(807)")
            ComboBox6.Items.Add("小港區(812)")
            ComboBox6.Items.Add("仁武區(814)")
            ComboBox6.Items.Add("岡山區(820)")
            ComboBox6.Items.Add("阿蓮區(822)")
            ComboBox6.Items.Add("燕巢區(824)")
            ComboBox6.Items.Add("梓官區(826)")
            ComboBox6.Items.Add("永安區(828)")
            ComboBox6.Items.Add("鳳山區(830)")
            ComboBox6.Items.Add("林園區(832)")
            ComboBox6.Items.Add("大樹區(840)")
            ComboBox6.Items.Add("美濃區(843)")
            ComboBox6.Items.Add("內門區(845)")
            ComboBox6.Items.Add("甲仙區(847)")
            ComboBox6.Items.Add("那瑪夏(849)")
            ComboBox6.Items.Add("茄萣區(852)")
            ComboBox6.Items.Add("苓雅區(802)")
            ComboBox6.Items.Add("鼓山區(804)")
            ComboBox6.Items.Add("前鎮區(806)")
            ComboBox6.Items.Add("楠梓區(811)")
            ComboBox6.Items.Add("左營區(813)")
            ComboBox6.Items.Add("大社區(815)")
            ComboBox6.Items.Add("路竹區(821)")
            ComboBox6.Items.Add("田寮區(823)")
            ComboBox6.Items.Add("橋頭區(825)")
            ComboBox6.Items.Add("彌陀區(827)")
            ComboBox6.Items.Add("湖內區(829)")
            ComboBox6.Items.Add("大寮區(831)")
            ComboBox6.Items.Add("鳥松區(833)")
            ComboBox6.Items.Add("旗山區(842)")
            ComboBox6.Items.Add("六龜區(844)")
            ComboBox6.Items.Add("杉林區(846)")
            ComboBox6.Items.Add("桃源區(848)")
            ComboBox6.Items.Add("茂林區(851)")
        End If
        If ComboBox5.Text = "臺中市(66)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("中 區(400)")
            ComboBox6.Items.Add("南 區(402)")
            ComboBox6.Items.Add("北 區(404)")
            ComboBox6.Items.Add("東 區(401)")
            ComboBox6.Items.Add("西 區(403)")
            ComboBox6.Items.Add("北屯區(406)")
            ComboBox6.Items.Add("南屯區(408)")
            ComboBox6.Items.Add("大里區(412)")
            ComboBox6.Items.Add("烏日區(414)")
            ComboBox6.Items.Add("后里區(421)")
            ComboBox6.Items.Add("東勢區(423)")
            ComboBox6.Items.Add("新社區(426)")
            ComboBox6.Items.Add("大雅區(428)")
            ComboBox6.Items.Add("大肚區(432)")
            ComboBox6.Items.Add("龍井區(434)")
            ComboBox6.Items.Add("清水區(436)")
            ComboBox6.Items.Add("外埔區(438)")
            ComboBox6.Items.Add("西屯區(407)")
            ComboBox6.Items.Add("太平區(411)")
            ComboBox6.Items.Add("霧峰區(413)")
            ComboBox6.Items.Add("豐原區(420)")
            ComboBox6.Items.Add("石岡區(422)")
            ComboBox6.Items.Add("和平區(424)")
            ComboBox6.Items.Add("潭子區(427)")
            ComboBox6.Items.Add("神岡區(429)")
            ComboBox6.Items.Add("沙鹿區(433)")
            ComboBox6.Items.Add("梧棲區(435)")
            ComboBox6.Items.Add("大甲區(437)")
            ComboBox6.Items.Add("大安區(439)")
        End If
        If ComboBox5.Text = "臺南市(67)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("中西區(700)")
            ComboBox6.Items.Add("南 區(702)")
            ComboBox6.Items.Add("東 區(701)")
            ComboBox6.Items.Add("北 區(704)")
            ComboBox6.Items.Add("安平區(708)")
            ComboBox6.Items.Add("安南區(709)")
            ComboBox6.Items.Add("歸仁區(711)")
            ComboBox6.Items.Add("左鎮區(713)")
            ComboBox6.Items.Add("楠西區(715)")
            ComboBox6.Items.Add("仁德區(717)")
            ComboBox6.Items.Add("龍崎區(719)")
            ComboBox6.Items.Add("麻豆區(721)")
            ComboBox6.Items.Add("西港區(723)")
            ComboBox6.Items.Add("將軍區(725)")
            ComboBox6.Items.Add("北門區(727)")
            ComboBox6.Items.Add("後壁區(731)")
            ComboBox6.Items.Add("東山區(733)")
            ComboBox6.Items.Add("下營區(735)")
            ComboBox6.Items.Add("鹽水區(737)")
            ComboBox6.Items.Add("大內區(742)")
            ComboBox6.Items.Add("新市區(744)")
            ComboBox6.Items.Add("永康區(710)")
            ComboBox6.Items.Add("新化區(712)")
            ComboBox6.Items.Add("玉井區(714)")
            ComboBox6.Items.Add("南化區(716)")
            ComboBox6.Items.Add("關廟區(718)")
            ComboBox6.Items.Add("官田區(720)")
            ComboBox6.Items.Add("佳里區(722)")
            ComboBox6.Items.Add("七股區(724)")
            ComboBox6.Items.Add("學甲區(726)")
            ComboBox6.Items.Add("新營區(730)")
            ComboBox6.Items.Add("白河區(732)")
            ComboBox6.Items.Add("六甲區(734)")
            ComboBox6.Items.Add("柳營區(736)")
            ComboBox6.Items.Add("善化區(741)")
            ComboBox6.Items.Add("山上區(743)")
            ComboBox6.Items.Add("安定區(745)")
        End If
        If ComboBox5.Text = "金門縣(71)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("金沙鎮(700)")
            ComboBox6.Items.Add("金湖鎮(701)")
            ComboBox6.Items.Add("金城鎮(704)")
            ComboBox6.Items.Add("烏坵鄉(709)")
            ComboBox6.Items.Add("金寧鄉(702)")
            ComboBox6.Items.Add("烈嶼鄉(708)")
        End If
        If ComboBox5.Text = "連江縣(72)" Then
            ComboBox6.Items.Clear()
            ComboBox6.Items.Add("北竿鄉(210)")
            ComboBox6.Items.Add("東引鄉(212)")
            ComboBox6.Items.Add("南竿鄉(209)")
            ComboBox6.Items.Add("莒光鄉(211)")
        End If
    End Sub

    Private Sub ComboBox7_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ComboBox7.SelectedIndexChanged, ComboBox15.SelectedIndexChanged
        If ComboBox7.Text = "新北市(01)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("金山區(208)")
            ComboBox8.Items.Add("汐止區(221)")
            ComboBox8.Items.Add("石碇區(223)")
            ComboBox8.Items.Add("平溪區(226)")
            ComboBox8.Items.Add("貢寮區(228)")
            ComboBox8.Items.Add("坪林區(232)")
            ComboBox8.Items.Add("永和區(234)")
            ComboBox8.Items.Add("土城區(236)")
            ComboBox8.Items.Add("樹林區(238)")
            ComboBox8.Items.Add("三重區(241)")
            ComboBox8.Items.Add("泰山區(243)")
            ComboBox8.Items.Add("蘆洲區(247)")
            ComboBox8.Items.Add("八里區(249)")
            ComboBox8.Items.Add("三芝區(252)")
            ComboBox8.Items.Add("板橋區(220)")
            ComboBox8.Items.Add("深坑區(222)")
            ComboBox8.Items.Add("瑞芳區(224)")
            ComboBox8.Items.Add("雙溪區(227)")
            ComboBox8.Items.Add("新店區(231)")
            ComboBox8.Items.Add("烏來區(233)")
            ComboBox8.Items.Add("中和區(235)")
            ComboBox8.Items.Add("三峽區(237)")
            ComboBox8.Items.Add("鶯歌區(239)")
            ComboBox8.Items.Add("新莊區(242)")
            ComboBox8.Items.Add("林口區(244)")
            ComboBox8.Items.Add("五股區(248)")
            ComboBox8.Items.Add("淡水區(251)")
            ComboBox8.Items.Add("石門區(253)")
            ComboBox8.Items.Add("萬里區(207)")
        End If
        If ComboBox7.Text = "宜蘭縣(02)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("宜蘭市(260)")
            ComboBox8.Items.Add("頭城鎮(261)")
            ComboBox8.Items.Add("壯圍鄉(263)")
            ComboBox8.Items.Add("羅東鎮(265)")
            ComboBox8.Items.Add("大同鄉(267)")
            ComboBox8.Items.Add("冬山鄉(269)")
            ComboBox8.Items.Add("南澳鄉(272)")
            ComboBox8.Items.Add("礁溪鄉(262)")
            ComboBox8.Items.Add("員山鄉(264)")
            ComboBox8.Items.Add("三星鄉(266)")
            ComboBox8.Items.Add("五結鄉(268)")
            ComboBox8.Items.Add("蘇澳鎮(270)")
        End If
        If ComboBox7.Text = "桃園市(03)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("中壢市(320)")
            ComboBox8.Items.Add("平鎮市(324)")
            ComboBox8.Items.Add("楊梅鎮(326)")
            ComboBox8.Items.Add("觀音鄉(328)")
            ComboBox8.Items.Add("龜山鄉(333)")
            ComboBox8.Items.Add("大溪鎮(335)")
            ComboBox8.Items.Add("大園鄉(337)")
            ComboBox8.Items.Add("龍潭鄉(325)")
            ComboBox8.Items.Add("新屋鄉(327)")
            ComboBox8.Items.Add("桃園市(330)")
            ComboBox8.Items.Add("八德市(334)")
            ComboBox8.Items.Add("復興鄉(336)")
            ComboBox8.Items.Add("蘆竹鄉(338)")
        End If
        If ComboBox7.Text = "新竹縣(04)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("竹北市(302)")
            ComboBox8.Items.Add("湖口鄉(303)")
            ComboBox8.Items.Add("新埔鎮(305)")
            ComboBox8.Items.Add("芎林鄉(307)")
            ComboBox8.Items.Add("竹東鎮(310)")
            ComboBox8.Items.Add("橫山鄉(312)")
            ComboBox8.Items.Add("北埔鄉(314)")
            ComboBox8.Items.Add("新豐鄉(304)")
            ComboBox8.Items.Add("關西鎮(306)")
            ComboBox8.Items.Add("寶山鄉(308)")
            ComboBox8.Items.Add("五峰鄉(311)")
            ComboBox8.Items.Add("尖石鄉(313)")
            ComboBox8.Items.Add("峨眉鄉(315)")
        End If
        If ComboBox7.Text = "苗栗縣(05)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("竹南鎮(350)")
            ComboBox8.Items.Add("頭份鎮(351)")
            ComboBox8.Items.Add("南庄鄉(353)")
            ComboBox8.Items.Add("後龍鎮(356)")
            ComboBox8.Items.Add("苑裡鎮(358)")
            ComboBox8.Items.Add("造橋鄉(361)")
            ComboBox8.Items.Add("公館鄉(363)")
            ComboBox8.Items.Add("泰安鄉(365)")
            ComboBox8.Items.Add("三義鄉(367)")
            ComboBox8.Items.Add("卓蘭鎮(369)")
            ComboBox8.Items.Add("三灣鄉(352)")
            ComboBox8.Items.Add("獅潭鄉(354)")
            ComboBox8.Items.Add("通霄鎮(357)")
            ComboBox8.Items.Add("苗栗市(360)")
            ComboBox8.Items.Add("頭屋鄉(362)")
            ComboBox8.Items.Add("大湖鄉(364)")
            ComboBox8.Items.Add("銅鑼鄉(366)")
            ComboBox8.Items.Add("西湖鄉(368)")
        End If
        If ComboBox7.Text = "彰化縣(07)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("彰化市(500)")
            ComboBox8.Items.Add("芬園鄉(502)")
            ComboBox8.Items.Add("秀水鄉(504)")
            ComboBox8.Items.Add("福興鄉(506)")
            ComboBox8.Items.Add("和美鎮(508)")
            ComboBox8.Items.Add("員林鎮(510)")
            ComboBox8.Items.Add("永靖鄉(512)")
            ComboBox8.Items.Add("溪湖鎮(514)")
            ComboBox8.Items.Add("埔鹽鄉(516)")
            ComboBox8.Items.Add("北斗鎮(521)")
            ComboBox8.Items.Add("埤頭鄉(523)")
            ComboBox8.Items.Add("竹塘鄉(525)")
            ComboBox8.Items.Add("大城鄉(527)")
            ComboBox8.Items.Add("二水鄉(530)")
            ComboBox8.Items.Add("花壇鄉(503)")
            ComboBox8.Items.Add("鹿港鎮(505)")
            ComboBox8.Items.Add("線西鄉(507)")
            ComboBox8.Items.Add("伸港鄉(509)")
            ComboBox8.Items.Add("社頭鄉(511)")
            ComboBox8.Items.Add("埔心鄉(513)")
            ComboBox8.Items.Add("大村鄉(515)")
            ComboBox8.Items.Add("田中鎮(520)")
            ComboBox8.Items.Add("田尾鄉(522)")
            ComboBox8.Items.Add("溪州鄉(524)")
            ComboBox8.Items.Add("二林鎮(526)")
            ComboBox8.Items.Add("芳苑鄉(528)")
        End If
        If ComboBox7.Text = "南投縣(08)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("南投市(540)")
            ComboBox8.Items.Add("中寮鄉(541)")
            ComboBox8.Items.Add("國姓鄉(544)")
            ComboBox8.Items.Add("仁愛鄉(546)")
            ComboBox8.Items.Add("集集鎮(552)")
            ComboBox8.Items.Add("魚池鄉(555)")
            ComboBox8.Items.Add("竹山鎮(557)")
            ComboBox8.Items.Add("草屯鎮(542)")
            ComboBox8.Items.Add("埔里鎮(545)")
            ComboBox8.Items.Add("名間鄉(551)")
            ComboBox8.Items.Add("水里鄉(553)")
            ComboBox8.Items.Add("信義鄉(556)")
            ComboBox8.Items.Add("鹿谷鄉(558)")
        End If
        If ComboBox7.Text = "雲林縣(09)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("斗南鎮(630)")
            ComboBox8.Items.Add("大埤鄉(631)")
            ComboBox8.Items.Add("土庫鎮(633)")
            ComboBox8.Items.Add("東勢鄉(635)")
            ComboBox8.Items.Add("崙背鄉(637)")
            ComboBox8.Items.Add("斗六市(640)")
            ComboBox8.Items.Add("古坑鄉(646)")
            ComboBox8.Items.Add("西螺鎮(648)")
            ComboBox8.Items.Add("北港鎮(651)")
            ComboBox8.Items.Add("口湖鄉(653)")
            ComboBox8.Items.Add("元長鄉(655)")
            ComboBox8.Items.Add("虎尾鎮(632)")
            ComboBox8.Items.Add("褒忠鄉(634)")
            ComboBox8.Items.Add("台西鄉(636)")
            ComboBox8.Items.Add("麥寮鄉(638)")
            ComboBox8.Items.Add("林內鄉(643)")
            ComboBox8.Items.Add("莿桐鄉(647)")
            ComboBox8.Items.Add("二崙鄉(649)")
            ComboBox8.Items.Add("水林鄉(652)")
            ComboBox8.Items.Add("四湖鄉(654)")
        End If
        If ComboBox7.Text = "嘉義縣(10)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("番路鄉(602)")
            ComboBox8.Items.Add("梅山鄉(603)")
            ComboBox8.Items.Add("阿里山(605)")
            ComboBox8.Items.Add("大埔鄉(607)")
            ComboBox8.Items.Add("鹿草鄉(611)")
            ComboBox8.Items.Add("朴子市(613)")
            ComboBox8.Items.Add("六腳鄉(615)")
            ComboBox8.Items.Add("民雄鄉(621)")
            ComboBox8.Items.Add("溪口鄉(623)")
            ComboBox8.Items.Add("布袋鎮(625)")
            ComboBox8.Items.Add("竹崎鄉(604)")
            ComboBox8.Items.Add("中埔鄉(606)")
            ComboBox8.Items.Add("水上鄉(608)")
            ComboBox8.Items.Add("太保市(612)")
            ComboBox8.Items.Add("東石鄉(614)")
            ComboBox8.Items.Add("新港鄉(616)")
            ComboBox8.Items.Add("大林鎮(622)")
            ComboBox8.Items.Add("義竹鄉(624)")
        End If
        If ComboBox7.Text = "屏東縣(13)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("屏東市(900)")
            ComboBox8.Items.Add("三地門(901)")
            ComboBox8.Items.Add("瑪家鄉(903)")
            ComboBox8.Items.Add("里港鄉(905)")
            ComboBox8.Items.Add("鹽埔鄉(907)")
            ComboBox8.Items.Add("麟洛鄉(909)")
            ComboBox8.Items.Add("內埔鄉(912)")
            ComboBox8.Items.Add("潮州鎮(920)")
            ComboBox8.Items.Add("來義鄉(922)")
            ComboBox8.Items.Add("崁頂鄉(924)")
            ComboBox8.Items.Add("南州鄉(926)")
            ComboBox8.Items.Add("東港鎮(928)")
            ComboBox8.Items.Add("佳冬鄉(931)")
            ComboBox8.Items.Add("枋寮鄉(940)")
            ComboBox8.Items.Add("春日鄉(942)")
            ComboBox8.Items.Add("車城鄉(944)")
            ComboBox8.Items.Add("恆春鎮(946)")
            ComboBox8.Items.Add("霧台鄉(902)")
            ComboBox8.Items.Add("九如鄉(904)")
            ComboBox8.Items.Add("高樹鄉(906)")
            ComboBox8.Items.Add("長治鄉(908)")
            ComboBox8.Items.Add("竹田鄉(911)")
            ComboBox8.Items.Add("萬丹鄉(913)")
            ComboBox8.Items.Add("泰武鄉(921)")
            ComboBox8.Items.Add("萬巒鄉(923)")
            ComboBox8.Items.Add("新埤鄉(925)")
            ComboBox8.Items.Add("林邊鄉(927)")
            ComboBox8.Items.Add("琉球鄉(929)")
            ComboBox8.Items.Add("新園鄉(932)")
            ComboBox8.Items.Add("枋山鄉(941)")
            ComboBox8.Items.Add("獅子鄉(943)")
            ComboBox8.Items.Add("牡丹鄉(945)")
            ComboBox8.Items.Add("滿洲鄉(947)")
        End If
        If ComboBox7.Text = "台東縣(14)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("台東市(950)")
            ComboBox8.Items.Add("綠島鄉(951)")
            ComboBox8.Items.Add("延平鄉(953)")
            ComboBox8.Items.Add("鹿野鄉(955)")
            ComboBox8.Items.Add("海端鄉(957)")
            ComboBox8.Items.Add("東河鄉(959)")
            ComboBox8.Items.Add("長濱鄉(962)")
            ComboBox8.Items.Add("金峰鄉(964)")
            ComboBox8.Items.Add("達仁鄉(966)")
            ComboBox8.Items.Add("蘭嶼鄉(952)")
            ComboBox8.Items.Add("卑南鄉(954)")
            ComboBox8.Items.Add("關山鎮(956)")
            ComboBox8.Items.Add("池上鄉(958)")
            ComboBox8.Items.Add("成功鎮(961)")
            ComboBox8.Items.Add("太麻里(963)")
            ComboBox8.Items.Add("大武鄉(965)")
        End If
        If ComboBox7.Text = "花蓮縣(15)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("花蓮市(970)")
            ComboBox8.Items.Add("新城鄉(971)")
            ComboBox8.Items.Add("吉安鄉(973)")
            ComboBox8.Items.Add("鳳林鎮(975)")
            ComboBox8.Items.Add("豐濱鄉(977)")
            ComboBox8.Items.Add("萬榮鄉(979)")
            ComboBox8.Items.Add("卓溪鄉(982)")
            ComboBox8.Items.Add("秀林鄉(972)")
            ComboBox8.Items.Add("壽豐鄉(974)")
            ComboBox8.Items.Add("光復鄉(976)")
            ComboBox8.Items.Add("瑞穗鄉(978)")
            ComboBox8.Items.Add("玉里鎮(981)")
            ComboBox8.Items.Add("富里鄉(983)")
        End If
        If ComboBox7.Text = "澎湖縣(16)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("馬公市(880)")
            ComboBox8.Items.Add("西嶼鄉(881)")
            ComboBox8.Items.Add("七美鄉(883)")
            ComboBox8.Items.Add("湖西鄉(885)")
            ComboBox8.Items.Add("望安鄉(882)")
            ComboBox8.Items.Add("白沙鄉(884)")
        End If
        If ComboBox7.Text = "基隆市(17)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("仁愛區(200)")
            ComboBox8.Items.Add("信義區(201)")
            ComboBox8.Items.Add("中山區(203)")
            ComboBox8.Items.Add("暖暖區(205)")
            ComboBox8.Items.Add("中正區(202)")
            ComboBox8.Items.Add("安樂區(204)")
            ComboBox8.Items.Add("七堵區(206)")
        End If
        If ComboBox7.Text = "新竹市(18)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("東區/香山區/北區(300)")
        End If
        If ComboBox7.Text = "嘉義市(20)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("嘉義市(600)")
        End If
        If ComboBox7.Text = "臺北市(30)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("中正區(100)")
            ComboBox8.Items.Add("大同區(103)")
            ComboBox8.Items.Add("松山區(105)")
            ComboBox8.Items.Add("萬華區(108)")
            ComboBox8.Items.Add("士林區(111)")
            ComboBox8.Items.Add("內湖區(114)")
            ComboBox8.Items.Add("文山區(116)")
            ComboBox8.Items.Add("中山區(104)")
            ComboBox8.Items.Add("大安區(106)")
            ComboBox8.Items.Add("信義區(110)")
            ComboBox8.Items.Add("北投區(112)")
            ComboBox8.Items.Add("南港區(115)")
        End If
        If ComboBox7.Text = "高雄市(64)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("新興區(800)")
            ComboBox8.Items.Add("前金區(801)")
            ComboBox8.Items.Add("鹽埕區(803)")
            ComboBox8.Items.Add("旗津區(805)")
            ComboBox8.Items.Add("三民區(807)")
            ComboBox8.Items.Add("小港區(812)")
            ComboBox8.Items.Add("仁武區(814)")
            ComboBox8.Items.Add("岡山區(820)")
            ComboBox8.Items.Add("阿蓮區(822)")
            ComboBox8.Items.Add("燕巢區(824)")
            ComboBox8.Items.Add("梓官區(826)")
            ComboBox8.Items.Add("永安區(828)")
            ComboBox8.Items.Add("鳳山區(830)")
            ComboBox8.Items.Add("林園區(832)")
            ComboBox8.Items.Add("大樹區(840)")
            ComboBox8.Items.Add("美濃區(843)")
            ComboBox8.Items.Add("內門區(845)")
            ComboBox8.Items.Add("甲仙區(847)")
            ComboBox8.Items.Add("那瑪夏(849)")
            ComboBox8.Items.Add("茄萣區(852)")
            ComboBox8.Items.Add("苓雅區(802)")
            ComboBox8.Items.Add("鼓山區(804)")
            ComboBox8.Items.Add("前鎮區(806)")
            ComboBox8.Items.Add("楠梓區(811)")
            ComboBox8.Items.Add("左營區(813)")
            ComboBox8.Items.Add("大社區(815)")
            ComboBox8.Items.Add("路竹區(821)")
            ComboBox8.Items.Add("田寮區(823)")
            ComboBox8.Items.Add("橋頭區(825)")
            ComboBox8.Items.Add("彌陀區(827)")
            ComboBox8.Items.Add("湖內區(829)")
            ComboBox8.Items.Add("大寮區(831)")
            ComboBox8.Items.Add("鳥松區(833)")
            ComboBox8.Items.Add("旗山區(842)")
            ComboBox8.Items.Add("六龜區(844)")
            ComboBox8.Items.Add("杉林區(846)")
            ComboBox8.Items.Add("桃源區(848)")
            ComboBox8.Items.Add("茂林區(851)")
        End If
        If ComboBox7.Text = "臺中市(66)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("中 區(400)")
            ComboBox8.Items.Add("南 區(402)")
            ComboBox8.Items.Add("北 區(404)")
            ComboBox8.Items.Add("東 區(401)")
            ComboBox8.Items.Add("西 區(403)")
            ComboBox8.Items.Add("北屯區(406)")
            ComboBox8.Items.Add("南屯區(408)")
            ComboBox8.Items.Add("大里區(412)")
            ComboBox8.Items.Add("烏日區(414)")
            ComboBox8.Items.Add("后里區(421)")
            ComboBox8.Items.Add("東勢區(423)")
            ComboBox8.Items.Add("新社區(426)")
            ComboBox8.Items.Add("大雅區(428)")
            ComboBox8.Items.Add("大肚區(432)")
            ComboBox8.Items.Add("龍井區(434)")
            ComboBox8.Items.Add("清水區(436)")
            ComboBox8.Items.Add("外埔區(438)")
            ComboBox8.Items.Add("西屯區(407)")
            ComboBox8.Items.Add("太平區(411)")
            ComboBox8.Items.Add("霧峰區(413)")
            ComboBox8.Items.Add("豐原區(420)")
            ComboBox8.Items.Add("石岡區(422)")
            ComboBox8.Items.Add("和平區(424)")
            ComboBox8.Items.Add("潭子區(427)")
            ComboBox8.Items.Add("神岡區(429)")
            ComboBox8.Items.Add("沙鹿區(433)")
            ComboBox8.Items.Add("梧棲區(435)")
            ComboBox8.Items.Add("大甲區(437)")
            ComboBox8.Items.Add("大安區(439)")
        End If
        If ComboBox7.Text = "臺南市(67)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("中西區(700)")
            ComboBox8.Items.Add("南 區(702)")
            ComboBox8.Items.Add("東 區(701)")
            ComboBox8.Items.Add("北 區(704)")
            ComboBox8.Items.Add("安平區(708)")
            ComboBox8.Items.Add("安南區(709)")
            ComboBox8.Items.Add("歸仁區(711)")
            ComboBox8.Items.Add("左鎮區(713)")
            ComboBox8.Items.Add("楠西區(715)")
            ComboBox8.Items.Add("仁德區(717)")
            ComboBox8.Items.Add("龍崎區(719)")
            ComboBox8.Items.Add("麻豆區(721)")
            ComboBox8.Items.Add("西港區(723)")
            ComboBox8.Items.Add("將軍區(725)")
            ComboBox8.Items.Add("北門區(727)")
            ComboBox8.Items.Add("後壁區(731)")
            ComboBox8.Items.Add("東山區(733)")
            ComboBox8.Items.Add("下營區(735)")
            ComboBox8.Items.Add("鹽水區(737)")
            ComboBox8.Items.Add("大內區(742)")
            ComboBox8.Items.Add("新市區(744)")
            ComboBox8.Items.Add("永康區(710)")
            ComboBox8.Items.Add("新化區(712)")
            ComboBox8.Items.Add("玉井區(714)")
            ComboBox8.Items.Add("南化區(716)")
            ComboBox8.Items.Add("關廟區(718)")
            ComboBox8.Items.Add("官田區(720)")
            ComboBox8.Items.Add("佳里區(722)")
            ComboBox8.Items.Add("七股區(724)")
            ComboBox8.Items.Add("學甲區(726)")
            ComboBox8.Items.Add("新營區(730)")
            ComboBox8.Items.Add("白河區(732)")
            ComboBox8.Items.Add("六甲區(734)")
            ComboBox8.Items.Add("柳營區(736)")
            ComboBox8.Items.Add("善化區(741)")
            ComboBox8.Items.Add("山上區(743)")
            ComboBox8.Items.Add("安定區(745)")
        End If
        If ComboBox7.Text = "金門縣(71)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("金沙鎮(700)")
            ComboBox8.Items.Add("金湖鎮(701)")
            ComboBox8.Items.Add("金城鎮(704)")
            ComboBox8.Items.Add("烏坵鄉(709)")
            ComboBox8.Items.Add("金寧鄉(702)")
            ComboBox8.Items.Add("烈嶼鄉(708)")
        End If
        If ComboBox7.Text = "連江縣(72)" Then
            ComboBox8.Items.Clear()
            ComboBox8.Items.Add("北竿鄉(210)")
            ComboBox8.Items.Add("東引鄉(212)")
            ComboBox8.Items.Add("南竿鄉(209)")
            ComboBox8.Items.Add("莒光鄉(211)")
        End If
    End Sub
End Class